### ISSUE TITLE
2co1pu1co-error

### ISSUE THREAD

**Issue by adjursaaFoxGmail** [adjursaaFoxGmail/HalloWorld#17]
Fejl opdaget i forbindelse med pull request efterfulgt af commit

**Comment by adjuc** [comment]
Fik du ram på denne her også?

**Comment by kasperbirkelund** [comment]
Hej Anders, jeg forstår ikke informationen i denne besked. Jeg har i hvert fald lige 
1) pushet et commit
2) Lavet et PR
3) pushet et commit mere
4) verificeret at analysen er gået igennem

Gør du noget anderledes?

**Comment by adjuc** [comment]
Se nyt issue på CodeImproverTool
