### ISSUE TITLE
Ønske til udvidelse 

### ISSUE THREAD

**Issue by adjursaaFoxGmail** [adjursaaFoxGmail/HalloWorld#9]
Se chat

**Comment by star-kasperbirkelundlarsen** [comment]
Hvorfor opretter du ikke issues på CodeImprover? :-)

**Comment by adjuc** [comment]
Ja det er jo et af den slags spørgsml som jeg ville ønske jeg selv havde stillet (mig selv) :-)
I direkte forlængelse af dit gode spørgsmål  - så forestiller jeg mig at rykke over på CodeImproverTool med de interne issues (Fejl) og på CodeImprover med de issues som har en mulig interesse for vores kommende brugere (nye ønsker). 
Så får vi se om det kommer til at virke smart :-)

**Comment by kasperbirkelund** [comment]
Ook - jeg mente også CodeImproverTool ;-)

**Comment by adjuc** [comment]
Ok og ok til implmentering. 
Jeg har netop set en pull req rapport og det er helt som jeg har ønsket og forestillet mig. Takker :-)
